### ISSUE TITLE
CSS is whitespace sensitive

### ISSUE THREAD

**Issue by BrendanBuono** [BrendanBuono/Shio#4]
##Steps to Reproduce
* Type the following into the HTML Editor:
 ```html 
    <div class="test">Hello</div> 
 ```
* Type the following into the CSS Editor:
```css
.test{
background:red;
}
```
* Note the background turns red
* Add spacing before background in the CSS Editor
```css
.test{
    background:red;
}
```
* Note the background is no longer red
